# Generated by Django 2.1.4 on 2018-12-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181218_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='right_answers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='wrong_answers',
            field=models.IntegerField(null=True),
        ),
    ]
