# Generated by Django 2.1.4 on 2018-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181220_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AlterField(
            model_name='card',
            name='right_answers',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='card',
            name='wrong_answers',
            field=models.IntegerField(default='0'),
        ),
    ]
